version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5175:5432
    volumes:
      - ~/localcodedata/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}